apiVersion: v1
kind: Service
metadata:
  name: service1-svc
spec:
  type: ClusterIP
  selector:
    app: service1
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
